var constants = {
  ADD_PERSONALIZATION: "ADD_PERSONALIZATION",
  DEL_PERSONALIZATION: "DEL_PERSONALIZATION",
  ADD_HEADER_INPERSONAL: "ADD_HEADER_INPERSONAL",
  DEL_HEADER_INPERSONAL: "DEL_HEADER_INPERSONAL",
  SEND_MAIL: "SEND_MAIL",
  SEND_MAIL_SUCCESS: "SEND_MAIL_SUCCESS",
  SEND_MAIL_FAIL: "SEND_MAIL_FAIL",
  TOGGLE_SHOW_EVENT: "TOGGLE_SHOW_EVENT",
  ADD_EVENTS: "ADD_EVENTS",
};

module.exports = constants;
